version: "3"
services:
  game-server:
    image: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./game_server:/home/node/app
    ports:
      - "8080:8080"
    command: 'node game_server.js'
  web-server:
    image: nginx
    volumes:
      - ./pages:/usr/share/nginx/html
    ports:
      - "8000:80"
