apiVersion: v1
kind: Service
metadata:
  name: game-server
  labels:
    app: game-server
spec:
  ports:
  - port: 80
    name: game-server
  selector:
    app: game-server
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: game-server
spec:
  serviceName: game-server
  replicas: 3
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
      - name: game-server
        image: gcr.io/kick-it-down/game-server:latest
        ports:
        - containerPort: 8080
          name: game-server
        resources:
          requests:
            cpu: 0
