apiVersion: v1
kind: Service
metadata:
  labels:
    run: matching-server
  name: matching-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: matching-server
  type: ClusterIP
