apiVersion: v1
kind: Service
metadata:
  labels:
    run: web-server
  name: web-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web-server
  type: ClusterIP
